### ISSUE TITLE
the faucet should respond `.on('transactionHash', ...)`

### ISSUE THREAD

**Issue by benjaminbollen** [mosaicdao/faucet#10]
using `npm i @types/web3` we ran into some issues to import the web3

motication for this ticket: when funding multiple addresses in the tests, it is desirable for all funding transaction to get sent together, so that they can get mined together; reducing the overall wait time for the test to start.

**Comment by schemar** [comment]
I think this is a duplicate of #6

**Comment by schemar** [comment]
I think this is a duplicate of #6 @benjaminbollen

**Comment by benjaminbollen** [comment]
agreed
