### ISSUE TITLE
Update faucet for new chains

### ISSUE THREAD

**Issue by benjaminbollen** [mosaicdao/faucet#12]
:warning: You can ask @benjaminbollen if you require SSH access.

### New Test Nets
1407 and 1406 are new testnet chains. We want to enable the faucet *with base tokens* for them so that we can use them.
That means they need to be funded with base tokens on the side chains.

* You need to create new keys for the new chains (see the README or ask @schemar).
* You need to ask Bala to fund the new accounts.
* You need to know which ports on the mosaic-chains machine forward to which chain node (ask @benjaminbollen or @schemar if you don't know how to find this out).

ℹ️ To get inspiration you can look at the existing configs for other chains.
ℹ️ If you forget the password we decided on for the accounts, please call @benjaminbollen or @schemar on zoom.

### Ropsten
Make sure ropsten is still sufficiently funded as well.

### Remove
Remove 200 and 1414 from the config and don't start them with the faucet.

**Comment by benjaminbollen** [comment]
⚠️ probably only Martin or I have ssh-access to the node

**Comment by manand86** [comment]
JLP to Enterprise...engage!

**Comment by schemar** [comment]
@gulshanvasnani I don't think the faucet is running with the new chains enabled. Can you confirm that the faucet should be running and that all relevant accounts are funded?

**Comment by schemar** [comment]
Change is not required anymore according to the associated PR.
