### ISSUE TITLE
Run a robust faucet and document the usage

### ISSUE THREAD

**Issue by schemar** [mosaicdao/faucet#16]
This is a follow-up ticket to #12.

#12 already created all necessary keys, funded them, and started the faucet to run with the new chains
(@gulshanvasnani please confirm).

Tasks in this issue:

* [x] Run the faucet in a way where it automatically restarts whenever the process crashes.
* [x] Document *privately for OST* how to use the faucet (especially address and port).

**Comment by schemar** [comment]
@gulshanvasnani can you please confirm the assumptions above?

**Comment by schemar** [comment]
First, I had to fix the linting setup. See #17.

**Comment by schemar** [comment]
I am working on figuring out the right ports. Comparing with the nodes machine.

**Comment by schemar** [comment]
@benjaminbollen your nodes server does not have enough memory to run nodes for four chains (3, 1406, 1407, 1414). How to proceed?

**Comment by schemar** [comment]
Do you want to increase the node or should we run fewer chains on this one?

**Comment by benjaminbollen** [comment]
let's only run testnet nodes, so excluding 1414 already

**Comment by schemar** [comment]
In order for the faucet to automatically restart, there must be an option to run it non-interactively. It requires hidden input of multiple passwords (one per faucet), which must become non-interactive.

**Comment by schemar** [comment]
The faucet is documented here: https://hackmd.io/WIzt8cufQXG2JsMEmY6lYA

**Comment by schemar** [comment]
If you pick this up for review, please check the documentation link: https://hackmd.io/WIzt8cufQXG2JsMEmY6lYA
You may also check how the faucet is running on the server in `tmux`. I created a script `endless.sh` which restarts the faucet whenever it crashes.

**Comment by gulshanvasnani** [comment]
I liked the `endless.sh` script to restart the faucet.
I tried the faucet for all the 3 chainId's. The error is `error: could not fill address`. Could you also check  whether wiring for port forwarding is correct.

**Comment by 0xsarvesh** [comment]
Documentation LGTM  ✅  
I couldn't review other things due to lack of access to the server.

**Comment by schemar** [comment]
> I liked the `endless.sh` script to restart the faucet.
> I tried the faucet for all the 3 chainId's. The error is `error: could not fill address`. Could you also check whether wiring for port forwarding is correct.

That's weird, it worked for me 🤔 I will check the server to see the error log.

**Comment by schemar** [comment]
Someone messed with the SSH connection on the faucet server inside tmux. I restarted it. Can you please try again @gulshanvasnani ?

**Comment by schemar** [comment]
Also added a warning to https://hackmd.io/WIzt8cufQXG2JsMEmY6lYA

**Comment by deepesh-kn** [comment]
> If you pick this up for review, please check the documentation link: https://hackmd.io/WIzt8cufQXG2JsMEmY6lYA

Documentation looks good 👍 

> You may also check how the faucet is running on the server in `tmux`. I created a script `endless.sh` which restarts the faucet whenever it crashes.

I was not able to find `endless.sh`. Can you point it to me?

**Comment by schemar** [comment]
ssh into faucet, then:

```bash
cd ./faucet
cat endless.sh
```

**Comment by pgev** [comment]
Robust implementation (+ detailed documentation) for the faucet is in place (the corresponding PR #17 is merged).

Closing this ticket: new tickets should be created for next improvements and bug fixes for the faucet.
