### ISSUE TITLE
Faucet should have a compatible license

### ISSUE THREAD

**Issue by schemar** [mosaicdao/faucet#7]
Faucet depends on libraries like Web3.
Faucet is currently licensed under MIT, which is most likely incompatible to Web3.

Check the licenses of the dependencies and select a valid license for Faucet.
Faucet should have  the least restricted valid license possible.

**Comment by benjaminbollen** [comment]
faucet is not altering the web3 code, and all code is open-source; closing because irrelevant given faucet is not a commmercial product, just helper code
